#include<stdio.h>
int main(void)
{
    int i;
    unsigned long long int a;
    while(scanf("%llu",&a)!=EOF)
    {
        i=1;
        printf("Hailstone generated by %llu:\n",a);
        printf("%llu ",a);
        while(1)
        {
            if(a%2==0&&a!=2)
            {
                a=a/2;
                printf("%llu ",a);
                i++;
            }
            if(a%2==1&&a!=1)
            {
                a=3*a+1;
                printf("%llu ",a);
                i++;
            }
            if(a==2)
            {
                ++i;
                printf("1\nNumber of hailstone generated:%d\n\n",i);
                break;
            }
        }
    }
    return 0;
}
